<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SpecializationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $specializations = [
            ['specialization' => 'Pre-baccalaureate Maritime', 'strand_id' => '3', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Agricultural Crops Production (NC I)', 'strand_id' => '5', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Agricultural Crops Production (NC II)', 'strand_id' => '5', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Agricultural Crops Production (NC III)', 'strand_id' => '5', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Animal Health Care Management (NC III)', 'strand_id' => '5', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Animal Production (Poultry-Chicken) (NC II)', 'strand_id' => '5', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Animal Production (Ruminants) (NC II)', 'strand_id' => '5', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Animal Production (Swine) (NC II)', 'strand_id' => '5', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Aquaculture (NC II)', 'strand_id' => '5', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Artificial Insemination (Ruminants) (NC II)', 'strand_id' => '5', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Artificial Insemination (Swine) (NC II)', 'strand_id' => '5', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Fish Capture (NC II)', 'strand_id' => '5', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Fishing Gear Repair and Maintenance (NC III)', 'strand_id' => '5', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Fish-Products Packaging (NC II)', 'strand_id' => '5', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Fish Wharf Operation (NC I)', 'strand_id' => '5', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Food Processing (NC II)', 'strand_id' => '5', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Horticulture (NC III)', 'strand_id' => '5', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Organic Agriculture (NC II)', 'strand_id' => '5', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Pest Management (NC II)', 'strand_id' => '5', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Rice Machinery Operation (NC II)', 'strand_id' => '5', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Rubber Processing (NC II)', 'strand_id' => '5', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Rubber Production (NC II)', 'strand_id' => '5', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Slaughtering Operations (NC II)', 'strand_id' => '5', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Attractions and Theme Parks (NC II)', 'strand_id' => '6', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Barbering (NC II)', 'strand_id' => '6', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Bartending (NC II)', 'strand_id' => '6', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Beauty/Nail Care (NC II)', 'strand_id' => '6', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Bread and Pastry Production (NC II)', 'strand_id' => '6', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Caregiving (NC II)', 'strand_id' => '6', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Commercial Cooking (NC III)', 'strand_id' => '6', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Cookery (NC II)', 'strand_id' => '6', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Dressmaking (NC II)', 'strand_id' => '6', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Events Management Services (NC III)', 'strand_id' => '6', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Fashion Design (Apparel) (NC III)', 'strand_id' => '6', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Food and Beverage Services (NC II)', 'strand_id' => '6', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Front Office Services (NC II)', 'strand_id' => '6', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Hairdressing (NC II)', 'strand_id' => '6', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Hairdressing (NC III)', 'strand_id' => '6', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Handicraft (Basketry, Macrame) (Non-NC)', 'strand_id' => '6', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Handicraft (Fashion Accessories, Paper Craft) (Non-NC)', 'strand_id' => '6', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Handicraft (Needlecraft) (Non-NC)', 'strand_id' => '6', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Handicraft (Woodcraft, Leathercraft) (Non-NC)', 'strand_id' => '6', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Housekeeping (NC II)', 'strand_id' => '6', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Local Guiding Services (NC II)', 'strand_id' => '6', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Tailoring (NC II)', 'strand_id' => '6', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Tourism Promotion Services (NC II)', 'strand_id' => '6', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Travel Services (NC II)', 'strand_id' => '6', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Wellness Massage (NC II)', 'strand_id' => '6', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Animation (NC II)', 'strand_id' => '7', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Broadband Installation (Fixed Wireless Systems) (NC II)', 'strand_id' => '7', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Broadband Installation (Fixed Wireless Systems) (NC II)', 'strand_id' => '7', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Computer Programming (.net Technology)  (NC III)', 'strand_id' => '7', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Computer Programming (Java) (NC III)', 'strand_id' => '7', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Computer Programming (Oracle Database) (NC III)', 'strand_id' => '7', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Computer Systems Servicing (NC II)', 'strand_id' => '7', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Contact Center Services (NC II)', 'strand_id' => '7', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Illustration (NC II)', 'strand_id' => '7', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Medical Transcription (NC II)', 'strand_id' => '7', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Technical Drafting (NC II)', 'strand_id' => '7', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Telecom OSP and Subscriber Line Installation (Copper Cable/POTS and DSL) (NC II)', 'strand_id' => '7', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Telecom OSP Installation (Fiber Optic Cable) (NC II)', 'strand_id' => '7', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Automotive Servicing (NC I)', 'strand_id' => '8', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Automotive Servicing (NC II)', 'strand_id' => '8', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Carpentry (NC II)', 'strand_id' => '8', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Carpentry (NC III)', 'strand_id' => '8', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Construction Painting (NC II)', 'strand_id' => '8', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Domestic Refrigeration and Airconditioning (DOMRAC) Servicing (NC II)', 'strand_id' => '8', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Driving (NC II)', 'strand_id' => '8', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Electrical Installation and Maintenance (NC II)', 'strand_id' => '8', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Electric Power Distribution Line Construction (NC II)', 'strand_id' => '8', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Electronic Products Assembly and Servicing (NC II)', 'strand_id' => '8', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Furniture Making (Finishing) (NC II)', 'strand_id' => '8', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Instrumentation and Control Servicing (NC II)', 'strand_id' => '8', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Gas Metal Arc Welding (GMAW) (NC II)', 'strand_id' => '8', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Gas Tungsten Arc Welding (GTAW) (NC II)', 'strand_id' => '8', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Machining (NC I)', 'strand_id' => '8', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Machining (NC II)', 'strand_id' => '8', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Masonry (NC II)', 'strand_id' => '8', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Mechatronics Servicing (NC II)', 'strand_id' => '8', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Motorcycle/Small Engine Servicing (NC II)', 'strand_id' => '8', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Plumbing (NC I)', 'strand_id' => '8', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Refrigeration and Air-Conditioning (Packaged Air-Conditioning Unit [PACU]/Commercial Refrigeration Equipment [CRE]) Servicing (NC III)', 'strand_id' => '8', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Shielded Metal Arc Welding (NC I)', 'strand_id' => '8', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Shielded Metal Arc Welding (NC II)', 'strand_id' => '8', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Tile Setting (NC II)', 'strand_id' => '8', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Transmission Line Installation and Maintenance (NC II)', 'strand_id' => '8', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Navigational Watch 1', 'strand_id' => '9', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Navigational Watch 2', 'strand_id' => '9', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Navigational Watch 3', 'strand_id' => '9', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Engine Watch 1', 'strand_id' => '9', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Engine Watch 2', 'strand_id' => '9', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Safety 1', 'strand_id' => '9', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Safety 2', 'strand_id' => '9', 'created_at' => now(), 'updated_at' => now()],  
            ['specialization' => 'Ship’s Catering Services (NC I)', 'strand_id' => '9', 'created_at' => now(), 'updated_at' => now()],  
        ];

        DB::table('specializations')->insert($specializations);
    }
}
