<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SubjectSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('subjects')->delete();

        $subjects = [
            ['code' => 'MATH', 'title' => 'Math', 'unit' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'LAAS', 'title' => 'Language Arts', 'unit' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SCI', 'title' => 'Science', 'unit' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'KPE', 'title' => 'Physical Education', 'unit' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'MT', 'title' => 'Mother Tounge', 'unit' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'FIL', 'title' => 'Filipino', 'unit' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'ENG', 'title' => 'English', 'unit' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'MATHS', 'title' => 'Mathematics', 'unit' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'EsP', 'title' => 'Edukasyon sa Pagpapakatao', 'unit' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'MSC', 'title' => 'Music', 'unit' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'TLE', 'title' => 'Technology and Livelihood Education', 'unit' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'OC', 'title' => 'Oral Communication', 'unit' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'GM', 'title' => 'General Mathematics', 'unit' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'CLPW', 'title' => '21st Century Literature in Modern World', 'unit' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'OM', 'title' => 'Organization and Management', 'unit' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'RW', 'title' => 'Reading and Writing', 'unit' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'PS', 'title' => 'Physical Science', 'unit' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SP', 'title' => 'Statistics and Probability', 'unit' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'PR1', 'title' => 'Practical Research 1', 'unit' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'PR2', 'title' => 'Practical Research 2', 'unit' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'COMED', 'title' => 'Computer Engineering Drafting & Design', 'unit' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'DISS', 'title' => 'Disciplines and Ideas in the Social Sciences', 'unit' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'CALC', 'title' => 'Pre-Calculus', 'unit' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'IHH', 'title' => 'Intro to Hotel HouseKeeping', 'unit' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'IOC', 'title' => 'Introduction to Computing', 'unit' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'CP1', 'title' => 'Computer Programming 1', 'unit' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'TCW', 'title' => 'The Contemporary World', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'EUT1', 'title' => 'Euthenics 1', 'unit' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'TEM', 'title' => 'The Entrepreneurial Mind', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'MMW', 'title' => 'Mathematics in the Modern World', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'NSTP1', 'title' => 'National Service Training Program 1', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'PE1', 'title' => 'Physical Education 1', 'unit' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'UST', 'title' => 'Understanding the Self', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'CP2', 'title' => 'Computer Programming 2', 'unit' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'DS1', 'title' => 'Discrete Structures 1 (Discrete Mathematics)', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'AA', 'title' => 'Art Appreciation', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'ETH', 'title' => 'Ethics', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'NSTP2', 'title' => 'National Service Training Program 2', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'PE2', 'title' => 'Physical Education 2', 'unit' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'PC1', 'title' => 'Purposive Communication 1', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'STS', 'title' => 'Science, Technology, and Society', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SAM1', 'title' => 'Systems Administration and Maintenance 1', 'unit' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'DSA', 'title' => 'Data Structures and Algorithms', 'unit' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'RLW', 'title' => 'Rizal’s Life and Works', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'PE3', 'title' => 'Physical Education 3', 'unit' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'RHP', 'title' => 'Readings in Philippine History', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'HCI', 'title' => 'Human-Computer Interaction', 'unit' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'ITE1', 'title' => 'IT Elective 1', 'unit' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'PT1', 'title' => 'Platform Technology 1 (Operating Systems)', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'IM1', 'title' => 'Information Management', 'unit' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'PC2', 'title' => 'Purposive Communication 2', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'PE4', 'title' => 'Physical Education 4', 'unit' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'ITE2', 'title' => 'IT Elective 2', 'unit' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'NT1', 'title' => 'Network Technology 1', 'unit' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'QM', 'title' => 'Quantitative Methods', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'TECH', 'title' => 'Technopreneurship', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SIA', 'title' => 'Systems Integration and Architecture', 'unit' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'IP1', 'title' => 'Integrative Programming 1', 'unit' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'ADET', 'title' => 'Application Development and Emerging Technologies', 'unit' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'GB', 'title' => 'Great Books', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'IAS', 'title' => 'Information Assurance and Security (Cybersecurity Fundamentals)', 'unit' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'ADS', 'title' => 'Advanced Database Systems', 'unit' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'EDP', 'title' => 'Event-Driven Programming', 'unit' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'ITE3', 'title' => 'IT Elective 3', 'unit' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'DDC', 'title' => 'Data and Digital Communications (Data Communications)', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'PIIST', 'title' => 'Professional Issues in Information Systems and Technology', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'WST', 'title' => 'Web Systems and Technologies', 'unit' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'IAS', 'title' => 'Information Assurance and Security (Data Privacy)', 'unit' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'MIS', 'title' => 'Management Information Systems', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'ITCP1', 'title' => 'IT Capstone Project 1', 'unit' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'NT2', 'title' => 'Network Technology 2', 'unit' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'ASIA', 'title' => 'Advanced Systems Integration and Architecture', 'unit' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'EUT2', 'title' => 'Euthenics 2', 'unit' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'MST', 'title' => 'Mobile Systems and Technologies', 'unit' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'ITCP2', 'title' => 'It Capstone Project 2', 'unit' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'ITE4', 'title' => 'IT Elective 4', 'unit' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'CGP', 'title' => 'Computer Graphics Programming', 'unit' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'ITPRAC', 'title' => 'IT Practicum (486 hours)', 'unit' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'CC', 'title' => 'College Calculus', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'CSET1', 'title' => 'CS Elective 1', 'unit' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SQA', 'title' => 'Software Quality Assurance', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'MS', 'title' => 'Modeling and Simulation', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'TCA', 'title' => 'Theory of Computations with Automata', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'CSA', 'title' => 'Computer Systems Architecture', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'CO', 'title' => 'Computer Organization', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'GP', 'title' => 'Game Programming', 'unit' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'MR', 'title' => 'Methods of Research', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'PL', 'title' => 'Programming Languages', 'unit' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SE1', 'title' => 'Software Engineering 1', 'unit' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'CSPRAC', 'title' => 'CS Practicum (300 hours)', 'unit' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'CSET2', 'title' => 'CS Elective 2', 'unit' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'CST1', 'title' => 'CS Thesis 1', 'unit' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SE2', 'title' => 'Software Engineering 2', 'unit' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'CET3', 'title' => 'CS Elective 2', 'unit' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'AI', 'title' => 'Artificial Intelligence', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'QM', 'title' => 'Quantitative Methods (Data Analysis)', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'BM', 'title' => 'Basic Microeconomics', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'CPT', 'title' => 'Computer Productivity Tools', 'unit' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'PQT', 'title' => 'Productivity and Quality Tools', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'CP', 'title' => 'Counting and Pricing', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'FM', 'title' => 'Facilities Management', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'BL', 'title' => 'Business Law (Obligation and Contracts)', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'TX', 'title' => 'Taxation (Income Taxation)', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'LM', 'title' => 'Logistics Management', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'GGSR', 'title' => 'Good Governance and Social Responsibility', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'IBT', 'title' => 'International Business and Trade', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'OM', 'title' => 'Operations Management (TQM)', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'MA', 'title' => 'Managerial Accounting', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'HRM', 'title' => 'Human Resource Management', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SM', 'title' => 'Strategic Management', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'PP', 'title' => 'Panitikang Pilipino', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'EMS', 'title' => 'Environmental Management Systems', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'IMC', 'title' => 'Inventory Management and Control', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'PM', 'title' => 'Project Manaegement', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'FS', 'title' => 'Feasibility Study', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'EM', 'title' => 'Entrepreneurial Management', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'FM', 'title' => 'Financial Management', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'MM', 'title' => 'Marketing Management', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'STOM', 'title' => 'Special Topics in Operations Management', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'PRAC', 'title' => 'Practicum (600 hours)', 'unit' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'MPTH', 'title' => 'Macro Perspective of Tourism and Hospitality', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'RMATSS', 'title' => 'Risk Management as Applied to Safety, Security, and Sanitation', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'KEBFP', 'title' => 'Kitchen Essentials and Basic Food Preparation', 'unit' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'PCTG', 'title' => 'Philippine Culture and Tourism Geography', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'MPTH', 'title' => 'Micro Perspective of Tourism and Hospitality', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'HFOOM', 'title' => 'Hotel Front Office Operations Management', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'PRCFSD', 'title' => 'Philippine Regional Cuisines with Food Styling and Design', 'unit' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'FLO', 'title' => 'Fundamentals in Lodging Operations', 'unit' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'FL1', 'title' => 'Foreign Language 1', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'QSMTH', 'title' => 'Quality Service Management in Tourism and Hospitality', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'ICFSD', 'title' => 'International Cuisines with Food Styling and Design', 'unit' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SCMHI', 'title' => 'ISupply Chain Management in Hospitality Industry', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'FFSO', 'title' => 'Fundamentals in Food Service Operations', 'unit' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'IMICEM', 'title' => 'Introduction ot Meetings Incentives, Conferences, and Events Management (MICE)', 'unit' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'FL2', 'title' => 'Foreign Language 2', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'OM', 'title' => 'Operations Management (TQM)', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'PABM', 'title' => 'Pastry Arts and Bakery Management', 'unit' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'PBTTH', 'title' => 'Applied Business Tools and Technologies in Hospitality', 'unit' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'PDAE', 'title' => 'Professional Development and Applied Ethics', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'THM', 'title' => 'Tourism and Hospitality Marketing', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'MDWTP', 'title' => 'Multicultural Diversity in Workplace for the Tourism Professional', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'COM', 'title' => 'Catering Operations Management', 'unit' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'EFPHI', 'title' => 'Ergonomics and Facilities Planning for Hospitality Industry', 'unit' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'MGFC', 'title' => 'Modern Gastronomy with Fusion of Cuisines', 'unit' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'LATH', 'title' => 'Legal Aspects in Tourism and Hospitality', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'ETH', 'title' => 'Entrepreneurship in Tourism and Hospitality', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SCFE', 'title' => 'Specialty Cuisine with Food Exhibit', 'unit' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'RH', 'title' => 'Research in Hospitality', 'unit' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'BSHMPRAC', 'title' => 'BSHM Practicum (600 hours)', 'unit' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'PLD', 'title' => 'Programming Logic and Design', 'unit' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'CCD', 'title' => 'College Calculus (Differential)', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'CE', 'title' => 'Chemistry for Engineers', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'CED', 'title' => 'Computer Engineering as a Discipline', 'unit' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'OOP', 'title' => 'Object-Oriented Programming', 'unit' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'CCI', 'title' => 'College Calculus (Integral)', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'POE', 'title' => 'Physics for Engineers', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'FEC', 'title' => 'Fundamentals of Electrical Circuits', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'ETCpE', 'title' => 'Emerging Technologies in CpE', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'DE', 'title' => 'Differential Equations', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'NM', 'title' => 'Numerical Methods', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'FEC', 'title' => 'Fundamentals of Electronic Circuits', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SD', 'title' => 'Software Design', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'CpEET1', 'title' => 'CpE Elective 1', 'unit' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'LCD', 'title' => 'Logic Circuits and Design', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'CAD', 'title' => 'Computer-Aided Drafting', 'unit' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'CEDD', 'title' => 'Computer Engineering Drafting and Design', 'unit' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'EE', 'title' => 'Engineering Economics', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'FES', 'title' => 'Feedback and Control Systems', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'BOHS', 'title' => 'Basic Occupational Health and Safety', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'MICROP', 'title' => 'Microprocessors', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'CpEET2', 'title' => 'CpE Elective 2', 'unit' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'INTROHDL', 'title' => 'Introduction to HDL', 'unit' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'DSP', 'title' => 'Digital Signal Processing', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'CpEPRAC', 'title' => 'Cpe Practicum (300 hours)', 'unit' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'CD1', 'title' => 'Capstone Design 1', 'unit' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'CNS', 'title' => 'Computer Network and Security', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'CpELPP', 'title' => 'CpE Laws and Professional Practice', 'unit' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'CpEET3', 'title' => 'CpE Elective 3', 'unit' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'ES', 'title' => 'Embedded Systems', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'CD2', 'title' => 'Capstone Design 2', 'unit' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'INTROCM', 'title' => 'Introduction to Communication Media', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'COMMCS', 'title' => 'Communication, Culture, and Society', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'DP', 'title' => 'Digital Photography', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'BPP', 'title' => 'Broadcasting Principles and Practices', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'JPP', 'title' => 'Journalism Principles and Practices', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'CT', 'title' => 'Communication Theory', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'DC', 'title' => 'Development Communication', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'BCD', 'title' => 'Brand Communication and Design', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'CMLE', 'title' => 'Communication Media Laws and Ethics', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'RDHM', 'title' => 'Risk, Disaster, and Humanitarian Communication', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SMPP', 'title' => 'Social Media Principles and Practices', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'APP', 'title' => 'Advertising Principles and Practices', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'MJ', 'title' => 'Multimedia Journalism', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'COMMR', 'title' => 'Communication Research', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'WRNM', 'title' => 'Writing for New Media', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'DLMD', 'title' => 'Digital Learning Materials Development', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SMMTCC', 'title' => 'Social Media and Mobile Technology for Communication Campaigns', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'INTERN', 'title' => 'Internship (300 Hours OJT)', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'CP', 'title' => 'Communication Planning', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'WL', 'title' => 'World Literature', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'DP', 'title' => 'Digital Publishing', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'WCM', 'title' => 'Web Content Management', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SP1', 'title' => 'Thesis/ Special Project 1', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'TH/SP1', 'title' => 'Thesis/ Special Project 1', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'COMMM', 'title' => 'Communication Management', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'KNOWM', 'title' => 'Knowledge Management', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'TH/SP2', 'title' => 'Thesis/ Special Project 2', 'unit' => 3, 'created_at' => now(), 'updated_at' => now()],
        ];

        DB::table('subjects')->insert($subjects);
    }
}
