<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SubjectSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('subjects')->delete();

        $subjects = [
            ['code' => 'MATH', 'title' => 'Math', 'description' => 'Apply knowledge of computing, science, and mathematics appropriate to the discipline. Understand best practices and standards and their applications.', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'LAAS', 'title' => 'Language Arts', 'description' => 'Analyze complex problems, and identify and define the computing requirements appropriate to its solution. Identify and analyze user needs and take them into account in the selection, creation, evaluation, and administration of computer-based systems.', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SCI', 'title' => 'Science', 'description' => 'Design, implement, and evaluate computer-based systems, processes, components, or programs to meet desired needs and requirements under various constraints.', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'KPE', 'title' => 'Physical Education', 'description' => 'Integrate IT-based solutions into the user environment effectively. Apply knowledge through the use of current techniques, skills, tools, and practices necessary for the IT profession.', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'MT', 'title' => 'Mother Tounge', 'description' => 'Function effectively as a member or leader of a development team recognizing the different roles within a team to accomplish a common goal.', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'FIL', 'title' => 'Filipino', 'description' => 'Communicate effectively with the computing community and with society at large about complex computing activities through logical writing, presentations, and clear instructions.', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'ENG', 'title' => 'English', 'description' => 'Analyze the local and global impact of computing information technology on individuals, organizations, and society.', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'MATHS', 'title' => 'Mathematics', 'description' => 'Understand professional, ethical, legal, security and social issues and responsibilities in the utilization of information technology.', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'EsP', 'title' => 'Edukasyon sa Pagpapakatao', 'description' => 'Recognize the need for and engage in planning self-learning and improving performance as a foundation for continuing professional development.', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'MSC', 'title' => 'Music', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'TLE', 'title' => 'Technology and Livelihood Education', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'OC', 'title' => 'Oral Communication', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'GM', 'title' => 'General Mathematics', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'CLPW', 'title' => '21st Century Literature in Modern World', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'OM', 'title' => 'Organization and Management', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'RW', 'title' => 'Reading and Writing', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'PS', 'title' => 'Physical Science', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SP', 'title' => 'Statistics and Probability', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'PR1', 'title' => 'Practical Research 1', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'PR2', 'title' => 'Practical Research 2', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'COMED', 'title' => 'Computer Engineering Drafting & Design', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'DISS', 'title' => 'Disciplines and Ideas in the Social Sciences', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'CALC', 'title' => 'Pre-Calculus', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'IHH', 'title' => 'Intro to Hotel HouseKeeping', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'IOC', 'title' => 'Introduction to Computing', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'CP1', 'title' => 'Computer Programming 1', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'TCW', 'title' => 'The Contemporary World', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'EUT1', 'title' => 'Euthenics 1', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'TEM', 'title' => 'The Entrepreneurial Mind', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'MMW', 'title' => 'Mathematics in the Modern World', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'NSTP1', 'title' => 'National Service Training Program 1', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'PE1', 'title' => 'Physical Education 1', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'UST', 'title' => 'Understanding the Self', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'CP2', 'title' => 'Computer Programming 2', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'DS1', 'title' => 'Discrete Structures 1 (Discrete Mathematics)', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'AA', 'title' => 'Art Appreciation', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'ETH', 'title' => 'Ethics', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'NSTP2', 'title' => 'National Service Training Program 2', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'PE2', 'title' => 'Physical Education 2', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'PC1', 'title' => 'Purposive Communication 1', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'STS', 'title' => 'Science, Technology, and Society', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SAM1', 'title' => 'Systems Administration and Maintenance 1', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'DSA', 'title' => 'Data Structures and Algorithms', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'RLW', 'title' => 'Rizal’s Life and Works', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'PE3', 'title' => 'Physical Education 3', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'RHP', 'title' => 'Readings in Philippine History', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'HCI', 'title' => 'Human-Computer Interaction', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'ITE1', 'title' => 'IT Elective 1', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'PT1', 'title' => 'Platform Technology 1 (Operating Systems)', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'IM1', 'title' => 'Information Management', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'PC2', 'title' => 'Purposive Communication 2', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'PE4', 'title' => 'Physical Education 4', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'ITE2', 'title' => 'IT Elective 2', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'NT1', 'title' => 'Network Technology 1', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'QM', 'title' => 'Quantitative Methods', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'TECH', 'title' => 'Technopreneurship', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SIA', 'title' => 'Systems Integration and Architecture', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'IP1', 'title' => 'Integrative Programming 1', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'ADET', 'title' => 'Application Development and Emerging Technologies', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'GB', 'title' => 'Great Books', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'IAS', 'title' => 'Information Assurance and Security (Cybersecurity Fundamentals)', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'ADS', 'title' => 'Advanced Database Systems', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'EDP', 'title' => 'Event-Driven Programming', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'ITE3', 'title' => 'IT Elective 3', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'DDC', 'title' => 'Data and Digital Communications (Data Communications)', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'PIIST', 'title' => 'Professional Issues in Information Systems and Technology', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'WST', 'title' => 'Web Systems and Technologies', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'IAS', 'title' => 'Information Assurance and Security (Data Privacy)', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'MIS', 'title' => 'Management Information Systems', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'ITCP1', 'title' => 'IT Capstone Project 1', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'NT2', 'title' => 'Network Technology 2', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'ASIA', 'title' => 'Advanced Systems Integration and Architecture', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'EUT2', 'title' => 'Euthenics 2', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'MST', 'title' => 'Mobile Systems and Technologies', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'ITCP2', 'title' => 'It Capstone Project 2', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'ITE4', 'title' => 'IT Elective 4', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'CGP', 'title' => 'Computer Graphics Programming', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'ITPRAC', 'title' => 'IT Practicum (486 hours)', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'CC', 'title' => 'College Calculus', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'CSET1', 'title' => 'CS Elective 1', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SQA', 'title' => 'Software Quality Assurance', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'MS', 'title' => 'Modeling and Simulation', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'TCA', 'title' => 'Theory of Computations with Automata', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'CSA', 'title' => 'Computer Systems Architecture', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'CO', 'title' => 'Computer Organization', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'GP', 'title' => 'Game Programming', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'MR', 'title' => 'Methods of Research', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'PL', 'title' => 'Programming Languages', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SE1', 'title' => 'Software Engineering 1', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'CSPRAC', 'title' => 'CS Practicum (300 hours)', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'CSET2', 'title' => 'CS Elective 2', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'CST1', 'title' => 'CS Thesis 1', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SE2', 'title' => 'Software Engineering 2', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'CET3', 'title' => 'CS Elective 2', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'AI', 'title' => 'Artificial Intelligence', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'QM', 'title' => 'Quantitative Methods (Data Analysis)', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'BM', 'title' => 'Basic Microeconomics', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'CPT', 'title' => 'Computer Productivity Tools', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'PQT', 'title' => 'Productivity and Quality Tools', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'CP', 'title' => 'Counting and Pricing', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'FM', 'title' => 'Facilities Management', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'BL', 'title' => 'Business Law (Obligation and Contracts)', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'TX', 'title' => 'Taxation (Income Taxation)', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'LM', 'title' => 'Logistics Management', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'GGSR', 'title' => 'Good Governance and Social Responsibility', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'IBT', 'title' => 'International Business and Trade', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'OM', 'title' => 'Operations Management (TQM)', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'MA', 'title' => 'Managerial Accounting', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'HRM', 'title' => 'Human Resource Management', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SM', 'title' => 'Strategic Management', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'PP', 'title' => 'Panitikang Pilipino', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'EMS', 'title' => 'Environmental Management Systems', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'IMC', 'title' => 'Inventory Management and Control', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'PM', 'title' => 'Project Manaegement', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'FS', 'title' => 'Feasibility Study', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'EM', 'title' => 'Entrepreneurial Management', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'FM', 'title' => 'Financial Management', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'MM', 'title' => 'Marketing Management', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'STOM', 'title' => 'Special Topics in Operations Management', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'PRAC', 'title' => 'Practicum (600 hours)', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'MPTH', 'title' => 'Macro Perspective of Tourism and Hospitality', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'RMATSS', 'title' => 'Risk Management as Applied to Safety, Security, and Sanitation', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'KEBFP', 'title' => 'Kitchen Essentials and Basic Food Preparation', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'PCTG', 'title' => 'Philippine Culture and Tourism Geography', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'MPTH', 'title' => 'Micro Perspective of Tourism and Hospitality', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'HFOOM', 'title' => 'Hotel Front Office Operations Management', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'PRCFSD', 'title' => 'Philippine Regional Cuisines with Food Styling and Design', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'FLO', 'title' => 'Fundamentals in Lodging Operations', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'FL1', 'title' => 'Foreign Language 1', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'QSMTH', 'title' => 'Quality Service Management in Tourism and Hospitality', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'ICFSD', 'title' => 'International Cuisines with Food Styling and Design', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SCMHI', 'title' => 'ISupply Chain Management in Hospitality Industry', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'FFSO', 'title' => 'Fundamentals in Food Service Operations', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'IMICEM', 'title' => 'Introduction ot Meetings Incentives, Conferences, and Events Management (MICE)', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'FL2', 'title' => 'Foreign Language 2', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'OM', 'title' => 'Operations Management (TQM)', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'PABM', 'title' => 'Pastry Arts and Bakery Management', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'PBTTH', 'title' => 'Applied Business Tools and Technologies in Hospitality', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'PDAE', 'title' => 'Professional Development and Applied Ethics', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'THM', 'title' => 'Tourism and Hospitality Marketing', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'MDWTP', 'title' => 'Multicultural Diversity in Workplace for the Tourism Professional', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'COM', 'title' => 'Catering Operations Management', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'EFPHI', 'title' => 'Ergonomics and Facilities Planning for Hospitality Industry', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'MGFC', 'title' => 'Modern Gastronomy with Fusion of Cuisines', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'LATH', 'title' => 'Legal Aspects in Tourism and Hospitality', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'ETH', 'title' => 'Entrepreneurship in Tourism and Hospitality', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SCFE', 'title' => 'Specialty Cuisine with Food Exhibit', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'RH', 'title' => 'Research in Hospitality', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'BSHMPRAC', 'title' => 'BSHM Practicum (600 hours)', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'PLD', 'title' => 'Programming Logic and Design', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'CCD', 'title' => 'College Calculus (Differential)', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'CE', 'title' => 'Chemistry for Engineers', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'CED', 'title' => 'Computer Engineering as a Discipline', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'OOP', 'title' => 'Object-Oriented Programming', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'CCI', 'title' => 'College Calculus (Integral)', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'POE', 'title' => 'Physics for Engineers', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'FEC', 'title' => 'Fundamentals of Electrical Circuits', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'ETCpE', 'title' => 'Emerging Technologies in CpE', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'DE', 'title' => 'Differential Equations', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'NM', 'title' => 'Numerical Methods', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'FEC', 'title' => 'Fundamentals of Electronic Circuits', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SD', 'title' => 'Software Design', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'CpEET1', 'title' => 'CpE Elective 1', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'LCD', 'title' => 'Logic Circuits and Design', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'CAD', 'title' => 'Computer-Aided Drafting', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'CEDD', 'title' => 'Computer Engineering Drafting and Design', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'EE', 'title' => 'Engineering Economics', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'FES', 'title' => 'Feedback and Control Systems', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'BOHS', 'title' => 'Basic Occupational Health and Safety', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'MICROP', 'title' => 'Microprocessors', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'CpEET2', 'title' => 'CpE Elective 2', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'INTROHDL', 'title' => 'Introduction to HDL', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'DSP', 'title' => 'Digital Signal Processing', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'CpEPRAC', 'title' => 'Cpe Practicum (300 hours)', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'CD1', 'title' => 'Capstone Design 1', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'CNS', 'title' => 'Computer Network and Security', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'CpELPP', 'title' => 'CpE Laws and Professional Practice', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'CpEET3', 'title' => 'CpE Elective 3', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'ES', 'title' => 'Embedded Systems', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'CD2', 'title' => 'Capstone Design 2', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'INTROCM', 'title' => 'Introduction to Communication Media', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'COMMCS', 'title' => 'Communication, Culture, and Society', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'DP', 'title' => 'Digital Photography', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'BPP', 'title' => 'Broadcasting Principles and Practices', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'JPP', 'title' => 'Journalism Principles and Practices', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'CT', 'title' => 'Communication Theory', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'DC', 'title' => 'Development Communication', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'BCD', 'title' => 'Brand Communication and Design', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'CMLE', 'title' => 'Communication Media Laws and Ethics', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'RDHM', 'title' => 'Risk, Disaster, and Humanitarian Communication', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SMPP', 'title' => 'Social Media Principles and Practices', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'APP', 'title' => 'Advertising Principles and Practices', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'MJ', 'title' => 'Multimedia Journalism', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'COMMR', 'title' => 'Communication Research', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'WRNM', 'title' => 'Writing for New Media', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'DLMD', 'title' => 'Digital Learning Materials Development', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SMMTCC', 'title' => 'Social Media and Mobile Technology for Communication Campaigns', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'INTERN', 'title' => 'Internship (300 Hours OJT)', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'CP', 'title' => 'Communication Planning', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'WL', 'title' => 'World Literature', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'DP', 'title' => 'Digital Publishing', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'WCM', 'title' => 'Web Content Management', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SP1', 'title' => 'Thesis/ Special Project 1', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'TH/SP1', 'title' => 'Thesis/ Special Project 1', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'COMMM', 'title' => 'Communication Management', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'KNOWM', 'title' => 'Knowledge Management', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'TH/SP2', 'title' => 'Thesis/ Special Project 2', 'description' => 'N/A', 'created_at' => now(), 'updated_at' => now()],
        ];

        DB::table('subjects')->insert($subjects);
    }
}
